### ISSUE TITLE
Missing `node` in spawn command on windows

### ISSUE THREAD

**Issue by Bartvds** [RobLoach/docpad-plugin-grunt#9]
When I use this plugin I get this error:

```
error: Something went wrong with the action
error: An error occured:
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

So I looked into the code, and this line needs a 'node' command to work (as the shebang does nothing on windows): 

```
command = [@path.join rootPath, gruntPath]
```

https://github.com/RobLoach/docpad-plugin-grunt/blob/master/src/grunt.plugin.coffee#L52

Then it works as expected.

(well, small detail: it needs an extra newline: the 'Running "xyz" task' message gets appended to the progress bar's line:

```
FooPerforming generate: generateBefore at 5/10 50% ========================-------------------------Running "echo" task
echo!

Done, without errors.
```

**Comment by interpaul** [comment]
Plugin still not working on Windows

**Comment by interpaul** [comment]
I use own working build.
In package.json:

```json
"docpad-plugin-grunt": "git://github.com/interpaul/docpad-plugin-grunt.git#v211compiled"
```

**Comment by RobLoach** [comment]
Hmm, interesting....

https://github.com/RobLoach/docpad-plugin-grunt/compare/master...interpaul:v211

But when you see https://github.com/RobLoach/docpad-plugin-grunt/blob/master/src/grunt.plugin.coffee#L55 , there is already the 'node' prefix. Know what's going on?

**Comment by interpaul** [comment]
Actually no.
For me plugin stops working after https://github.com/RobLoach/docpad-plugin-grunt/commit/6cff6a711844e8b93b4344fa5baac07c25fddf50

**Comment by RobLoach** [comment]
@interpaul Which version of node is it?

**Comment by interpaul** [comment]
v0.12.7

**Comment by RobLoach** [comment]
Do the tests pass for you on Windows?

```
git clone git@github.com:RobLoach/docpad-plugin-grunt.git
cd docpad-plugin-grunt
npm i
node_modules/.bin/cake test
```

**Comment by interpaul** [comment]
Test failed.

See movie:
![docpad-grunt](https://cloud.githubusercontent.com/assets/475929/9306899/e4d222c4-4503-11e5-9ba2-de617b4f030d.gif)

Final output:

```bash
coffee compile:
C:\Program Files\nodejs\node.exe c:\GitHub\docpad-plugin-grunt\node_modules\.bin
\coffee -co out src
c:\GitHub\docpad-plugin-grunt\node_modules\.bin\coffee:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by RobLoach** [comment]
Thanks for posting these movies :+1: . Quite helpful in debugging. What software are you using for them?

Unexpected token ILLEGAL is an interesting one, since it is CoffeeScript. Where is basedir= represented? I can't find it in my source.

**Comment by interpaul** [comment]
[LICEcap](http://www.cockos.com/licecap/) for screen to gif. Works both on Windows and MacOS.

As for basedir — I don't know, I'm just designer.
